### PR TITLE
Updating lab.py with event sketch.

### PR DESCRIPTION
**Pull request by plachenko**
A sketch of an ongoing "event". Adding a random event probability integer as well as a check if it's over a certain threshold. Might require database updates to track cheese per person as well as storyline progression and lines. A current cheese amount state on the user would be nice to have.

Would something like this be cool with you @okj ?

### CODE REVIEW

**Comment by plachenko** [comment]
I haven't tested this, so I wouldn't merge this request, just opening this as an idea.

**Comment by okj** [comment]
@plachenko Yeah this is a cool idea, have at it!

**Comment by plachenko** [comment]
Any advice for user state management for progression and line storage in the database? I was thinking of maybe having branching paths of dialogue in the future.

**Comment by okj** [comment]
> Any advice for user state management for progression and line storage in the database? I was thinking of maybe having branching paths of dialogue in the future.

You can use wait_for events in discordpy which could even handle multiple dialogues between users (Probably worth using this in the current cheese event too) Wouldn't need to store this in the database unless you had multi day events or something
https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.wait_for

>Also any advice for compositing images-- can you composite and post an image from a dataURI through python natively or with a library?

Honestly not sure. Feel free to implement a library if you come across one that accomplishes this.

**Pull request closed without merging**
